@rootAPI = http://localhost:8000/api/v1


#==== admin api

### create new admin

POST {{ rootAPI}}/admin
Content-Type: application/json
{
   "fName: 'Rajiv",
   "lName":'Kumar',
   "phone": "040405",
   "email": 'a@a.com',
   "password": "dfgesd",
   "address": null
   
}